---
# Installs Drone server

- name: Create a volume
  docker_volume:
    name: drone-server-data
  become: true

- name: Start Drone Server
  docker_container: 
    name: drone_server
    image: drone/drone:0.8
    state: started
    restart: true
    restart_policy: always
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    volumes:
      - drone-server-data:/var/lib/drone/
    env:
      DRONE_OPEN: "{{ drone_server_open }}"
      DRONE_ADMIN: "{{ drone_server_admins }}"
      DRONE_HOST: "{{ drone_server_host }}"
      DRONE_GITHUB: true
      DRONE_GITHUB_CLIENT: "{{ drone_server_github_client }}"
      DRONE_GITHUB_SECRET: "{{ drone_server_github_secret }}"
      DRONE_SECRET: "{{ drone_server_secret }}"
      DRONE_LETS_ENCRYPT: true
  become: true
