---
# Creates an user

- name: Create user '{{ common_username }}'
  user: name={{ common_username }} groups={{ common_user_groups }} shell=/bin/bash password={{ common_user_password | password_hash('sha512') }}

- name: Add sudo rights to '{{ common_username }}'
  user: name={{ common_username }} append=true groups=sudo
  when: common_sudo

- name: Install ssh key for '{{ common_username }}'
  authorized_key: user={{ common_username }} key={{ common_ssh_pubkey }}
  when: common_use_pki

- name: Enable sudoers includes  
  lineinfile: dest=/etc/sudoers regexp='^#includedir /etc/sudoers.d' line='#includedir /etc/sudoers.d'
  become: true
  when: common_sudo and common_passwordless_sudo

- name: Check if '{{ common_username }}' is a password-less sudoer
  stat: path=/etc/sudoers.d/{{ common_username }}
  register: passwordless_sudoer
  become: true

- name: Add '{{ common_username }}' to password-less sudoers
  shell: "echo '{{ common_username }} ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/{{ common_username }}"
  args:
    creates: "/etc/sudoers.d/{{ common_username }}"
  become: true
  when: common_sudo and common_passwordless_sudo

- name: Remove '{{ common_username }}' from password-less sudoers
  file: path="/etc/sudoers.d/{{ common_username }}" state=absent
  become: true
  when: passwordless_sudoer.stat.exists and (not common_sudo or not common_passwordless_sudo)
