# Harden default SSHD configuration
---

- name: Reduce login grace time
  lineinfile: dest=/etc/ssh/sshd_config regexp='^#LoginGraceTime' line='LoginGraceTime 30s'
  become: true
  notify: Restart sshd

- name: Disable Root Login
  lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line='PermitRootLogin no'
  become: true
  when: common_disable_root_login
  notify: Restart sshd

- name: Disable Password Authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp='^#PasswordAuthentication' line='PasswordAuthentication no'
  become: true
  when: disable_password_authentication and common_use_pki
  notify: Restart sshd
