---
# Installs Consul agent

- name: Create group
  group: name=consul state=present
  become: true

- name: Create user
  user:
    name: consul
    groups: consul
    system: true
    shell: /bin/false
    create_home: true
    home: /etc/consul.d
  become: true

- name: Install unzip
  apt: name=unzip state=latest update_cache=yes
  become: true

- name: Download and install Consul
  unarchive:
    creates: /usr/local/bin/consul
    src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /usr/local/bin/
    remote_src: yes
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Copy service template
  template:
    src: templates/consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: "u=rwx,g=rwx,o=rwx"
  become: true

- name: Create data directory
  file:
    path: /opt/consul
    state: directory
    owner: consul
    group: consul
    mode: 0775
    recurse: yes
  become: true

- name: Copy server configuration
  template:
    src: templates/server.hcl.j2
    dest: /etc/consul.d/server.hcl
    owner: consul
    group: consul
    mode: 0640
  become: true
  when: consul_server

- name: Copy client configuration
  template:
    src: templates/client.hcl.j2
    dest: /etc/consul.d/client.hcl
    owner: consul
    group: consul
    mode: 0640
  become: true
  when: not consul_server

- name: Start Consul
  systemd: name=consul enabled=yes state=restarted daemon_reload=true
  become: true

- name: Add Agent Token
  uri:
    url: http://127.0.0.1:8500/v1/acl/create
    method: PUT
    headers:
      X-Consul-Token: "{{ consul_acl_master_token }}"
    body: >
      {
        "ID": "{{ consul_acl_agent_token }}",
        "Name": "Agent Token",
        "Type": "client",
        "Rules": "node \"\" { policy = \"write\" } service \"\" { policy = \"write\" } agent \"\" { policy = \"write\" }"
      }
    body_format: json
  when: consul_server

- name: Allow listing of all nodes and DNS lookups
  uri:
    url: http://127.0.0.1:8500/v1/acl/update
    method: PUT
    headers:
      X-Consul-Token: "{{ consul_acl_master_token }}"
    body: >
      {
        "ID": "anonymous",
        "Name": "Anonymous Token",
        "Type": "client",
        "Rules": "node \"\" { policy = \"read\" } service \"consul\" { policy = \"read\" } service \"nomad\" { policy = \"read\" }"  service \"vault\" { policy = \"read\" }"
      }
    body_format: json
  when: consul_server
